# permissions for end users to edit kubefilers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefiler-editor-role
rules:
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilers/status
  verbs:
  - get
