# permissions for end users to view kubefilers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefiler-viewer-role
rules:
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilers/status
  verbs:
  - get
