# permissions for end users to view kubefilerexports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefilerexport-viewer-role
rules:
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilerexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilerexports/status
  verbs:
  - get
