# permissions for end users to view kubefilerportals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefilerportal-viewer-role
rules:
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilerportals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubefiler.ctera.com
  resources:
  - kubefilerportals/status
  verbs:
  - get
