apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubefiler-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/gateway_data"
---
apiVersion: kubefiler.ctera.com/v1alpha1
kind: KubeFiler
metadata:
  name: kubefiler-sample
spec:
  # Add fields here
  portal: kubefilerportal-sample
  storage:
    pvc:
      spec:
        storageClassName: manual
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
