//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFiler) DeepCopyInto(out *KubeFiler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFiler.
func (in *KubeFiler) DeepCopy() *KubeFiler {
	if in == nil {
		return nil
	}
	out := new(KubeFiler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFiler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerExport) DeepCopyInto(out *KubeFilerExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerExport.
func (in *KubeFilerExport) DeepCopy() *KubeFilerExport {
	if in == nil {
		return nil
	}
	out := new(KubeFilerExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFilerExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerExportList) DeepCopyInto(out *KubeFilerExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeFilerExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerExportList.
func (in *KubeFilerExportList) DeepCopy() *KubeFilerExportList {
	if in == nil {
		return nil
	}
	out := new(KubeFilerExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFilerExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerExportSpec) DeepCopyInto(out *KubeFilerExportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerExportSpec.
func (in *KubeFilerExportSpec) DeepCopy() *KubeFilerExportSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerExportStatus) DeepCopyInto(out *KubeFilerExportStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerExportStatus.
func (in *KubeFilerExportStatus) DeepCopy() *KubeFilerExportStatus {
	if in == nil {
		return nil
	}
	out := new(KubeFilerExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerList) DeepCopyInto(out *KubeFilerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeFiler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerList.
func (in *KubeFilerList) DeepCopy() *KubeFilerList {
	if in == nil {
		return nil
	}
	out := new(KubeFilerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFilerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPortal) DeepCopyInto(out *KubeFilerPortal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPortal.
func (in *KubeFilerPortal) DeepCopy() *KubeFilerPortal {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPortal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFilerPortal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPortalCredentialsSpec) DeepCopyInto(out *KubeFilerPortalCredentialsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPortalCredentialsSpec.
func (in *KubeFilerPortalCredentialsSpec) DeepCopy() *KubeFilerPortalCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPortalCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPortalList) DeepCopyInto(out *KubeFilerPortalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeFilerPortal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPortalList.
func (in *KubeFilerPortalList) DeepCopy() *KubeFilerPortalList {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPortalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeFilerPortalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPortalSpec) DeepCopyInto(out *KubeFilerPortalSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(KubeFilerPortalCredentialsSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPortalSpec.
func (in *KubeFilerPortalSpec) DeepCopy() *KubeFilerPortalSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPortalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPortalStatus) DeepCopyInto(out *KubeFilerPortalStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPortalStatus.
func (in *KubeFilerPortalStatus) DeepCopy() *KubeFilerPortalStatus {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPortalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerPvcSpec) DeepCopyInto(out *KubeFilerPvcSpec) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerPvcSpec.
func (in *KubeFilerPvcSpec) DeepCopy() *KubeFilerPvcSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerPvcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerSpec) DeepCopyInto(out *KubeFilerSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerSpec.
func (in *KubeFilerSpec) DeepCopy() *KubeFilerSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerStatus) DeepCopyInto(out *KubeFilerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerStatus.
func (in *KubeFilerStatus) DeepCopy() *KubeFilerStatus {
	if in == nil {
		return nil
	}
	out := new(KubeFilerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeFilerStorageSpec) DeepCopyInto(out *KubeFilerStorageSpec) {
	*out = *in
	if in.Pvc != nil {
		in, out := &in.Pvc, &out.Pvc
		*out = new(KubeFilerPvcSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeFilerStorageSpec.
func (in *KubeFilerStorageSpec) DeepCopy() *KubeFilerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(KubeFilerStorageSpec)
	in.DeepCopyInto(out)
	return out
}
